config/routes.rb
Firstwords::Application.routes.draw do
  devise_for :users

  get "game/setup"
  get "game/play"
	get "game/check"
  get "game/results"

  get "result/index"
  get "result/show"

  root :to => 'game#setup'
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :category, :height, :level, :link, :name, :width
end

app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :category, :correct, :date, :level, :patient, :user_id

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :is_admin
  # attr_accessible :title, :body

	has_many :results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def setup
  end

  def play

		# Only if params[:result] is nil
		if !params[:result]
			@result = Result.new
			@result.category = params[:category]
			@result.level = params[:level]
			@result.patient = params[:child]
			@result.date = Time.now
			@result.correct = 0

			if user_signed_in?
				@result.user_id = current_user.id
			end

		else
			@result = Result.new(params[:result])
		end

		@question = params[:question]

		# Pass cumm throughout steps
		if params[:cummulative]
			options = Picture.where("level <= ? AND category = ?", @result.level, @result.category)
			@cummulative = true
		else
			options = Picture.where("level = ? AND category = ?", @result.level, @result.category)
			@cummulative = false
		end

		offset = rand(options.count)
		@first = options.first(:offset => offset)

		offset2 = offset
		while offset2 == offset
			offset2 = rand(options.count)
		end

		@second = options.first(:offset => offset2)
		offset3 = rand(2)
		if offset3 == 0
			@random = @first.name
		else
			@random = @second.name
		end

  end

	def check
		@result = Result.new(params[:result])
		@question = params[:question]
		@cummulative = params[:cummulative]

		if params[:correct] == params[:guessed]
			flash[:notice] = "Correct!"
			@result.correct += 1
		else
			flash[:notice] = "Sorry, that wasn't right!"
		end
	end

	def results
		@result = Result.create(params[:result])
	end
end

app/controllers/result_controller.rb
class ResultController < ApplicationController
  def index
  end

  def show
		@results = Result.where("patient = ? AND user_id = ?", params[:name], current_user.id)
		@names = Result.where("user_id = ?", current_user.id).collect{|n| [n.patient, n.patient]}.uniq
		@name = [@results.first.patient, @results.first.patient]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/game/check.html.erb
<% if flash[:notice] == "Sorry, that wasn't right!" %>
	<%= image_tag("incorrect.jpg") %>
<% else %>
	<%= image_tag("correct.jpg") %>
<% end %>
<h1>Question <%= @question %> <%= flash[:notice] %></h1>

<% res = {:patient => @result.patient, :date => @result.date, :category => @result.category, :level => @result.level, :correct => @result.correct, :user_id => @result.user_id} %>

<br>
<% if @question.to_i > 4 %>
	<%= link_to "See Results", game_results_path(:result => res) %>
<% else %>
	<%= link_to "Next Question", game_play_path(:result => res, :cummulative => @cummulative, :question => @question.to_i + 1) %>
<% end %>

<br>
result<%= debug @result %><br>

app/views/game/play.html.erb
<h1>Question <%= @question %> of 5</h1>

<% res = {:patient => @result.patient, :date => @result.date, :category => @result.category, :level => @result.level, :correct => @result.correct, :user_id => @result.user_id} %>

<h2>Pick the <%= @random %>!</h2>
<%= link_to(image_tag(@first.link, :width => @first.width, :height => @first.height), game_check_path(:correct => @random, :guessed => @first.name, :result => res, :question => @question, :cummulative => @cummulative)) %><=====================>
<%= link_to(image_tag(@second.link, :width => @second.width, :height => @second.height), game_check_path(:correct => @random, :guessed => @second.name, :result => res, :question => @question, :cummulative => @cummulative)) %>

app/views/game/results.html.erb
<h1>Congratulations! You're done!</h1>
<%= @result.patient %> got <%= @result.correct %> correct out of 5!<br><br>

<% res = {:patient => @result.patient, :date => @result.date, :category => @result.category, :level => @result.level, :correct => @result.correct, :user_id => @result.user_id} %>

<%= link_to "Play Again?", root_path %><br>
<%= link_to "See all of #{@result.patient}'s results", result_show_path(:name => @result.patient) %>

app/views/game/setup.html.erb
<h1>First Words!</h1>
<p>Welcome to the First Words app, where you can challenge your child's decision making ability.</p>
<% if !user_signed_in? %>
	<p>Please <%= link_to "sign in", new_user_session_path %> to save your results.<p>
<% end %>

<%= form_tag(game_play_path, :method => 'get') do %>
	Select a level:
	<%= select_tag :level, options_for_select([1, 2, 3]) %><br>

	Select a category:
	<%= select_tag :category, options_for_select(Picture.all.collect{|p| [p.category, p.category]}.uniq.sort) %><br>

	Cummulative?
	<%= check_box_tag 'cummulative' %><br>

	<% if user_signed_in? %>
		Which child is playing?
		<%= text_field_tag :child %><br>
	<% end %>

	<%= hidden_field_tag "question", "1" %>

	<%= submit_tag "Let's Play!" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firstwords</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="user_nav">
		<% if user_signed_in? %>
			Signed in as <%= current_user.email %>. <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
		<% else %>
			<%= link_to "Sign In", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %>
		<% end %>
	</div>

	<%= yield %>

</body>
</html>

app/views/result/index.html.erb
<h1>Result#index</h1>
<p>Find me in app/views/result/index.html.erb</p>

app/views/result/show.html.erb
<% if !@results.empty? %>

	<h1>Results for <%= @results.first.patient %></h1>

	<table>
		<tr>
			<td>Name</td>
			<td>Date</td>
			<td>Category</td>
			<td>Level</td>
			<td>Correct</td>
		</tr>
		<% @results.each do |result| %>
			<tr>
				<td><%= result.patient %></td>
				<td><%= result.date %></td>
				<td><%= result.category %></td>
				<td><%= result.level %></td>
				<td><%= result.correct %></td>
			</tr>
		<% end %>
	</table>

	<%= form_tag(result_show_path, :method => 'get') do %>

		See results for someone else?
		<%= select_tag :name, options_for_select(@names, :selected => @name), :onchange => "this.form.submit();" %>
	<% end %>

	<%= link_to "Play Again?", root_path %>

<% else %>

	<h1>No results found!</h1>

<% end %>